### ISSUE TITLE
help 页面

### ISSUE THREAD

**Issue by wcbing** [mirrorz-org/mirrorz#104]
直接打开 https://mirrors.cernet.edu.cn/ 会跳转到 https://help.mirrors.cernet.edu.cn/
另外主界面是不是应该加一个help文档的入口，我没有找到，必须要手动输入网站进去吗？

**Comment by ZenithalHourlyRate** [comment]
@RalXYZ

**Comment by taoky** [comment]
我个人觉得现在的跳转是不太合理的（或者说要改的东西会更多）：

1. Help 页面没有跳回到 mirrorz 镜像列表的链接；
2. Mirrorz 也要做修改，包括 https://mirrors.cernet.edu.cn/about/ 里面的帮助，以及点击左上角 icon 之后地址栏会变成 `https://mirrors.cernet.edu.cn/` 这个行为也要改。

如果不跳转的话，确实要加一个帮助，而且要考虑加哪里（比如说侧边栏上？）

**Comment by wcbing** [comment]
> 2\. 点击左上角 icon 之后地址栏会变成 `https://mirrors.cernet.edu.cn/` 这个行为也要改。

因为那个是首页，本来就应该是这样的。但问题是直接访问首页它给你302跳转到help页面了（mirrorz不会），访问时只能先访问/list，这就很奇怪。
所以我的建议一是在「两个网站的」侧边栏加一个帮助跳转按钮，二是取消「教育网镜像站」这个奇怪的跳转。你这个也可以加上
> 1. Help 页面没有跳回到 mirrorz 镜像列表的链接；

**Comment by TechCiel** [comment]
@taoky 我的建议是取消掉重定向，在左边栏加一个

使用
帮助

然后新标签打开 help 站

**Comment by taoky** [comment]
Fixed in 4564c17688fb5988c0eacd5885fac81f456d9ccf.

**Comment by wcbing** [comment]
@taoky 你上个月提交 [这个修改](https://github.com/mirrorz-org/mirrorz/commit/418dd8609667496c889204710ba3967866279f39) 后，教育网的镜像一直没有帮助按钮，是不是那边没改 `config.json` ?😂

**Comment by taoky** [comment]
@wcbing 因为一些网络原因，我现在没有办法做修改，须待相关方修复后再部署。

**Comment by taoky** [comment]
@wcbing 修好了。
