### ISSUE TITLE
Link to rustup ISRC-ISCAS help is wrong

### ISSUE THREAD

**Issue by FantasqueX** [mirrorz-org/mirrorz#109]
https://mirrorz.org/list/rustup

Current link is https://mirror.iscas.ac.cn/help/rustup/, which returns 404..

The correct one is https://help.mirrors.cernet.edu.cn/rustup/?mirror=ISRC-ISCAS.

I would like to submit a patch, however, my local build only shows sjtu mirror. I cannot figure out what is wrong locally.

<img width="439" alt="image" src="https://github.com/mirrorz-org/mirrorz/assets/46747123/90991df8-2e71-4460-985e-098d095d07c4">

**Comment by taoky** [comment]
```
> curl https://mirror.iscas.ac.cn/.mirrorz/mirrorz.json | jq . | grep "/help/rustup"                          
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53032  100 53032    0     0   262k      0 --:--:-- --:--:-- --:--:--  262k
      "help": "/help/rustup/",
```

**Comment by taoky** [comment]
（这需要 ISCAS 镜像的维护者修改 mirrorz.json 中 help 一项的内容才能修复）

**Comment by taoky** [comment]
@yinjiayi
