### ISSUE TITLE
Please temporarily stop redirecting to NYIST mirror

### ISSUE THREAD

**Issue by Rongronggg9** [mirrorz-org/mirrorz#115]
https://mirror.nyist.edu.cn/news/mirror-maintenance-oct-9/

> 由于业务调整，镜像站储存阵列于2023-10-09 20:00 (UTC+8:00)开始重新构建，预计于3日后完成，未构建完成维护时间顺延。
>
> 在维护期间，所有请求将被重定向至[教育网联合镜像站](https://mirrors.cernet.edu.cn/)，pypi不受影响。

```console
$ curl -sIL https://mirrors.cernet.edu.cn/debian | grep -i location
location: https://mirror.nyist.edu.cn/debian
Location: https://mirrors.cernet.edu.cn/debian
......
```

**Comment by Palvef** [comment]
@Rongronggg9 针对该问题 NYIST已将请求重定向至USTC
