### ISSUE TITLE
Current status format cannot indicate mirrors of proxy_cache

### ISSUE THREAD

**Issue by iamNCJ** [mirrorz-org/mirrorz#71]
Currently `mirrors.status` can only have one main status, which includes `C` for cache and `R` for reverse proxy. However, most of the time we use a cached proxy for those mirrors, and this can not be indicated under this data format design. Possible solutions include changing `C` to proxy_cache or adding a new status.

**Comment by RalXYZ** [comment]
More specifically, we don't know whether `C` implies *proxy cache*. If not, then we think it is necessary to add a new status.

**Comment by ZenithalHourlyRate** [comment]
> More specifically, we don't know whether `C` implies _proxy cache_ or not. If not, then we think it is necessary to add a new status.

When adding `C`, I had https://github.com/sjtug/mirror-intel in my mind, so it is some implementation of proxy cache.

It is weird, though, to have some cache that has no proxy functionality.

`R` refers to pure reverse proxy with no cache, so on the other hand I added `C`.

**Comment by iamNCJ** [comment]
> > More specifically, we don't know whether `C` implies _proxy cache_ or not. If not, then we think it is necessary to add a new status.
> 
> When adding `C`, I had https://github.com/sjtug/mirror-intel in my mind, so it is some implementation of proxy cache.
> 
> It is weird, though, to have some cache that has no proxy functionality.
> 
> `R` refers to pure reverse proxy with no cache, so on the other hand I added `C`.

Thanks, we've got it. Maybe modifying the notes of the format in readme can help reduce the confusion.
